# Generated by Django 5.2.16 on 2026-07-23 03:50

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sku', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('unit', models.CharField(default='u', max_length=32)),
                ('stock', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=14)),
                ('reorder_level', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=14)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sku', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('color', models.CharField(blank=True, choices=[('DORADO', 'Dorado'), ('PLATEADO', 'Plateado'), ('OTRO', 'Otro')], max_length=16)),
                ('tipo', models.CharField(blank=True, max_length=128)),
                ('woo_product_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('active', models.BooleanField(default=True)),
                ('stock', models.IntegerField(default=0)),
                ('reorder_level', models.IntegerField(default=0)),
                ('is_generic', models.BooleanField(default=False, help_text='Producto genérico dorado/plateado para ítems sin mapeo.')),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['color', 'tipo'], name='inventory_p_color_43e186_idx'), models.Index(fields=['active', 'stock'], name='inventory_p_active_601afd_idx')],
            },
        ),
        migrations.CreateModel(
            name='KardexEntry',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_type', models.CharField(choices=[('PRODUCT', 'Producto'), ('MATERIAL', 'Material')], max_length=16)),
                ('movement', models.CharField(choices=[('IN', 'Entrada'), ('OUT', 'Salida'), ('ADJUST', 'Ajuste')], max_length=16)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14)),
                ('balance', models.DecimalField(decimal_places=3, max_digits=14)),
                ('reason', models.CharField(choices=[('DISPATCH', 'Despacho'), ('PURCHASE', 'Compra'), ('MANUAL_ADJUST', 'Ajuste manual'), ('PRODUCTION', 'Producción'), ('REFUND', 'Reembolso')], max_length=32)),
                ('ref_type', models.CharField(blank=True, max_length=64)),
                ('ref_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kardex_entries', to=settings.AUTH_USER_MODEL)),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='kardex', to='inventory.material')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='kardex', to='inventory.product')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['item_type', 'reason'], name='inventory_k_item_ty_5d3bba_idx'), models.Index(fields=['ref_type', 'ref_id'], name='inventory_k_ref_typ_3385b9_idx'), models.Index(fields=['product', 'created_at'], name='inventory_k_product_0cd40a_idx')],
            },
        ),
    ]
