# Generated by Django 5.2.16 on 2026-07-23 03:58

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('id_type', models.CharField(default='CC', max_length=16)),
                ('id_number', models.CharField(db_index=True, max_length=64)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=64)),
                ('address', models.CharField(blank=True, max_length=512)),
                ('city', models.CharField(blank=True, max_length=128)),
                ('alegra_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('alegra_synced', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('POR_GENERAR', 'Por generar'), ('ENVIANDO', 'Enviando'), ('GENERADA', 'Generada'), ('FALLIDA', 'Fallida'), ('ANULADA', 'Anulada')], db_index=True, default='POR_GENERAR', max_length=16)),
                ('alegra_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('number', models.CharField(blank=True, max_length=64)),
                ('cufe', models.CharField(blank=True, max_length=128)),
                ('pdf_url', models.URLField(blank=True)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('iva', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('last_error', models.TextField(blank=True)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('idempotency_key', models.CharField(max_length=128, unique=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='accounting.customer')),
                ('sale', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='sales.consolidatedsale')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('SOLICITADO', 'Solicitado'), ('NOTA_CREDITO_EMITIDA', 'Nota crédito emitida'), ('CERRADO', 'Cerrado')], db_index=True, default='SOLICITADO', max_length=32)),
                ('reason', models.TextField()),
                ('alegra_credit_note_id', models.CharField(blank=True, max_length=64)),
                ('manual_void_pending', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refunds_created', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='accounting.invoice')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='sales.consolidatedsale')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(fields=('id_type', 'id_number'), name='uq_customer_doc'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['status', 'created_at'], name='accounting__status_f9d294_idx'),
        ),
    ]
