# Generated by Django 5.2.16 on 2026-07-23 02:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geo', '0001_initial'),
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchJob',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_type', models.CharField(choices=[('GENERATE_SHIPMENTS', 'Generar guías'), ('FORMAT_ADDRESSES', 'Formatear direcciones'), ('MARK_SENT', 'Marcar enviados')], max_length=32)),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('RUNNING', 'En curso'), ('COMPLETED', 'Completado'), ('CANCELLED', 'Cancelado')], default='PENDING', max_length=16)),
                ('total', models.PositiveIntegerField(default=0)),
                ('done', models.PositiveIntegerField(default=0)),
                ('success', models.PositiveIntegerField(default=0)),
                ('failed', models.PositiveIntegerField(default=0)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batch_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BatchJobItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ref_type', models.CharField(blank=True, max_length=64)),
                ('ref_id', models.CharField(db_index=True, max_length=64)),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('RUNNING', 'En curso'), ('SUCCESS', 'Éxito'), ('FAILED', 'Fallido'), ('SKIPPED', 'Omitido')], default='PENDING', max_length=16)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('error', models.TextField(blank=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='logistics.batchjob')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('address_mirror', models.CharField(blank=True, max_length=512)),
                ('city_mirror', models.CharField(blank=True, max_length=128)),
                ('state_mirror', models.CharField(blank=True, max_length=128)),
                ('geo_state_code', models.CharField(blank=True, max_length=8)),
                ('address_formatted', models.CharField(blank=True, max_length=512)),
                ('do_not_ship', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('POR_GENERAR', 'Por generar guía'), ('GUIA_FALLIDA', 'Guía fallida'), ('LISTO_PARA_ENVIAR', 'Listo para enviar'), ('ENVIADO', 'Enviado'), ('REVISAR', 'Revisar / no enviar')], db_index=True, default='POR_GENERAR', max_length=24)),
                ('carrier', models.CharField(default='coordinadora', max_length=64)),
                ('service', models.CharField(default='ground', max_length=64)),
                ('tracking_number', models.CharField(blank=True, db_index=True, max_length=128)),
                ('label_url', models.URLField(blank=True)),
                ('shipping_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('generated_city', models.CharField(blank=True, max_length=128)),
                ('generated_state', models.CharField(blank=True, max_length=128)),
                ('generated_address', models.CharField(blank=True, max_length=512)),
                ('warning', models.BooleanField(default=False)),
                ('warning_detail', models.JSONField(blank=True, default=dict)),
                ('last_error', models.TextField(blank=True)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('envia_shipment_id', models.CharField(blank=True, max_length=128)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('geo_city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipments', to='geo.geocatalog')),
                ('sale', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shipment', to='sales.consolidatedsale')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'warning'], name='logistics_s_status_f3d8bf_idx'), models.Index(fields=['do_not_ship', 'status'], name='logistics_s_do_not__1ccbc0_idx')],
            },
        ),
    ]
