# Generated by Django 5.2.16 on 2026-07-23 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchjob',
            name='job_type',
            field=models.CharField(choices=[('GENERATE_SHIPMENTS', 'Generar guías'), ('FORMAT_ADDRESSES', 'Formatear direcciones'), ('MARK_SENT', 'Marcar enviados'), ('ISSUE_INVOICES', 'Emitir facturas')], max_length=32),
        ),
    ]
