# Generated by Django 5.2.6 on 2026-07-25 22:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ControlIndicator",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("key", models.CharField(max_length=64, unique=True)),
                ("label", models.CharField(max_length=255)),
                ("module", models.CharField(db_index=True, max_length=32)),
                ("description", models.CharField(blank=True, max_length=512)),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("COUNT", "Conteo"),
                            ("AMOUNT", "Monto"),
                            ("PERCENT", "Porcentaje"),
                            ("DAYS", "Días"),
                        ],
                        default="COUNT",
                        max_length=16,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("INFO", "Info"),
                            ("WARNING", "Warning"),
                            ("CRITICAL", "Crítico"),
                        ],
                        default="WARNING",
                        max_length=16,
                    ),
                ),
                (
                    "warn_threshold",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=16, null=True
                    ),
                ),
                (
                    "crit_threshold",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=16, null=True
                    ),
                ),
                ("target_url", models.CharField(blank=True, max_length=512)),
                ("visible", models.BooleanField(default=True)),
                ("roles", models.JSONField(blank=True, default=list)),
                ("order", models.IntegerField(default=0)),
            ],
            options={
                "ordering": ["order", "key"],
            },
        ),
        migrations.CreateModel(
            name="IndicatorSnapshot",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("value", models.DecimalField(decimal_places=2, max_digits=16)),
                (
                    "amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=16, null=True
                    ),
                ),
                ("captured_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "indicator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snapshots",
                        to="dashboard.controlindicator",
                    ),
                ),
            ],
            options={
                "ordering": ["-captured_at"],
                "indexes": [
                    models.Index(
                        fields=["indicator", "-captured_at"],
                        name="dashboard_i_indicat_85f0ae_idx",
                    )
                ],
            },
        ),
    ]
