# Generated by Django 5.2.6 on 2026-07-25 22:44

import apps.expenses.models
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("finance", "0002_bankimportbatch_date_range"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExpenseStatus",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("key", models.CharField(max_length=64, unique=True)),
                ("label", models.CharField(max_length=128)),
                ("order", models.IntegerField(default=0)),
                ("feeds_efe", models.BooleanField(default=False)),
                ("color", models.CharField(blank=True, max_length=32)),
                ("active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["order", "key"],
            },
        ),
        migrations.CreateModel(
            name="Expense",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=512)),
                ("concept", models.CharField(blank=True, max_length=512)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=16
                    ),
                ),
                ("expense_date", models.DateField(db_index=True)),
                ("payment_date", models.DateField(blank=True, null=True)),
                (
                    "attribution",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ADMINISTRATIVO", "Administrativo"),
                            ("VENTAS", "Ventas"),
                            ("OPERACIONAL", "Operacional"),
                            ("COMPARTIDO", "Compartido"),
                            ("NIAT", "NIAT"),
                        ],
                        max_length=24,
                    ),
                ),
                ("checked", models.BooleanField(default=False)),
                (
                    "iva_discountable",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                ("iva_already_discounted", models.BooleanField(default=False)),
                ("amortize", models.BooleanField(default=False)),
                (
                    "amortization_months",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("reconciled", models.BooleanField(default=False)),
                ("alegra_synced", models.BooleanField(default=False)),
                ("alegra_id", models.CharField(blank=True, max_length=64)),
                (
                    "accounting_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="expenses",
                        to="finance.accountingaccount",
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_expenses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "bank_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="expenses",
                        to="finance.bank",
                    ),
                ),
                (
                    "bank_movement",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="expense_links",
                        to="finance.bankmovement",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_expenses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "efe_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="expenses",
                        to="finance.financialaccount",
                    ),
                ),
                (
                    "responsible",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="responsible_expenses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="expenses",
                        to="expenses.expensestatus",
                    ),
                ),
            ],
            options={
                "ordering": ["-expense_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ExpenseAttachment",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("PAYMENT_PROOF", "Comprobante de pago"),
                            ("PROVIDER_INVOICE", "Factura del proveedor"),
                            ("OTHER", "Otro"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=apps.expenses.models.expense_attachment_upload_to
                    ),
                ),
                ("filename", models.CharField(max_length=255)),
                ("mime_type", models.CharField(blank=True, max_length=128)),
                (
                    "expense",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="expenses.expense",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="expense_attachments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ExpenseAmortizationEntry",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("period_month", models.PositiveSmallIntegerField()),
                ("period_year", models.PositiveIntegerField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=16)),
                (
                    "efe_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="amortization_entries",
                        to="finance.financialaccount",
                    ),
                ),
                (
                    "expense",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="amortization_entries",
                        to="expenses.expense",
                    ),
                ),
            ],
            options={
                "ordering": ["period_year", "period_month"],
                "indexes": [
                    models.Index(
                        fields=["period_year", "period_month", "efe_account"],
                        name="expenses_ex_period__6f7a1a_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("expense", "period_month", "period_year"),
                        name="uq_amort_period",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="expense",
            index=models.Index(
                fields=["status", "expense_date"], name="expenses_ex_status__ade858_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="expense",
            index=models.Index(
                fields=["reconciled", "expense_date"],
                name="expenses_ex_reconci_fe2ac7_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="expense",
            index=models.Index(
                fields=["iva_already_discounted"], name="expenses_ex_iva_alr_498fdc_idx"
            ),
        ),
    ]
