# Generated by Django 5.2.6 on 2026-07-25 23:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0001_initial"),
        ("finance", "0002_bankimportbatch_date_range"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="nature",
            field=models.CharField(
                choices=[
                    ("EMPRESA", "De la empresa"),
                    ("NOMINAL", "Nominal (no contable Seeds)"),
                ],
                db_index=True,
                default="EMPRESA",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="expense",
            name="on_behalf_of",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddIndex(
            model_name="expense",
            index=models.Index(
                fields=["nature", "expense_date"], name="expenses_ex_nature_49b5b7_idx"
            ),
        ),
    ]
