from __future__ import annotations

from apps.dashboard.models import ControlIndicator, IndicatorSeverity, IndicatorUnit

CATALOG: list[dict] = [
    # Expenses
    {
        "key": "gastos_sin_factura",
        "label": "Gastos sin factura",
        "module": "EXPENSES",
        "description": "Sin factura de proveedor o en FACTURA_SIN_SOPORTE",
        "unit": IndicatorUnit.COUNT,
        "severity": IndicatorSeverity.CRITICAL,
        "warn_threshold": 1,
        "crit_threshold": 5,
        "target_url": "/expenses?status_key=FACTURA_SIN_SOPORTE",
        "roles": ["ADMIN", "CONTABILIDAD", "SUPERVISOR"],
        "order": 10,
    },
    {
        "key": "gastos_sin_comprobante",
        "label": "Gastos sin comprobante",
        "module": "EXPENSES",
        "unit": IndicatorUnit.COUNT,
        "severity": IndicatorSeverity.WARNING,
        "warn_threshold": 1,
        "crit_threshold": 10,
        "target_url": "/expenses",
        "roles": ["ADMIN", "CONTABILIDAD", "SUPERVISOR"],
        "order": 20,
    },
    {
        "key": "gastos_sin_cuenta_efe",
        "label": "Gastos sin cuenta EFE",
        "module": "EXPENSES",
        "unit": IndicatorUnit.COUNT,
        "severity": IndicatorSeverity.CRITICAL,
        "warn_threshold": 1,
        "crit_threshold": 1,
        "target_url": "/expenses?feeds_efe=true",
        "roles": ["ADMIN", "CONTABILIDAD", "SUPERVISOR"],
        "order": 30,
    },
    {
        "key": "reembolsos_por_pagar",
        "label": "Reembolsos por pagar",
        "module": "EXPENSES",
        "unit": IndicatorUnit.COUNT,
        "severity": IndicatorSeverity.WARNING,
        "warn_threshold": 1,
        "crit_threshold": 20,
        "target_url": "/expenses?tab=reembolsos",
        "roles": ["ADMIN", "CONTABILIDAD", "SUPERVISOR"],
        "order": 40,
    },
    {
        "key": "cuentas_por_pagar",
        "label": "Cuentas por pagar",
        "module": "EXPENSES",
        "unit": IndicatorUnit.COUNT,
        "severity": IndicatorSeverity.WARNING,
        "warn_threshold": 1,
        "crit_threshold": 30,
        "target_url": "/expenses?status_key=CUENTAS_POR_PAGAR",
        "roles": ["ADMIN", "CONTABILIDAD", "SUPERVISOR"],
        "order": 50,
    },
    {
        "key": "iva_por_descontar",
        "label": "IVA por descontar",
        "module": "EXPENSES",
        "unit": IndicatorUnit.COUNT,
        "severity": IndicatorSeverity.INFO,
        "warn_threshold": 5,
        "crit_threshold": 50,
        "target_url": "/expenses?tab=iva",
        "roles": ["ADMIN", "CONTABILIDAD", "SUPERVISOR"],
        "order": 60,
    },
    {
        "key": "gastos_sin_conciliar",
        "label": "Gastos sin conciliar",
        "module": "EXPENSES",
        "unit": IndicatorUnit.COUNT,
        "severity": IndicatorSeverity.WARNING,
        "warn_threshold": 5,
        "crit_threshold": 25,
        "target_url": "/expenses?reconciled=false",
        "roles": ["ADMIN", "CONTABILIDAD", "SUPERVISOR"],
        "order": 70,
    },
    # Finance
    {
        "key": "movimientos_sin_clasificar",
        "label": "Movimientos sin clasificar",
        "module": "FINANCE",
        "unit": IndicatorUnit.COUNT,
        "severity": IndicatorSeverity.WARNING,
        "warn_threshold": 10,
        "crit_threshold": 100,
        "target_url": "/finance/movements",
        "roles": ["ADMIN", "CONTABILIDAD", "SUPERVISOR"],
        "order": 110,
    },
    {
        "key": "egresos_sin_gasto",
        "label": "Egresos sin gasto documentado",
        "module": "FINANCE",
        "unit": IndicatorUnit.COUNT,
        "severity": IndicatorSeverity.WARNING,
        "warn_threshold": 10,
        "crit_threshold": 50,
        "target_url": "/finance/movements",
        "roles": ["ADMIN", "CONTABILIDAD", "SUPERVISOR"],
        "order": 120,
    },
    # Accounting
    {
        "key": "facturas_fallidas",
        "label": "Facturas fallidas",
        "module": "ACCOUNTING",
        "unit": IndicatorUnit.COUNT,
        "severity": IndicatorSeverity.CRITICAL,
        "warn_threshold": 1,
        "crit_threshold": 1,
        "target_url": "/accounting?status=FALLIDA",
        "roles": ["ADMIN", "CONTABILIDAD", "SUPERVISOR"],
        "order": 210,
    },
    {
        "key": "facturas_por_generar",
        "label": "Facturas por generar",
        "module": "ACCOUNTING",
        "unit": IndicatorUnit.COUNT,
        "severity": IndicatorSeverity.WARNING,
        "warn_threshold": 20,
        "crit_threshold": 100,
        "target_url": "/accounting?status=POR_GENERAR",
        "roles": ["ADMIN", "CONTABILIDAD", "SUPERVISOR"],
        "order": 220,
    },
    {
        "key": "facturas_enviando_colgadas",
        "label": "Facturas ENVIANDO colgadas",
        "module": "ACCOUNTING",
        "unit": IndicatorUnit.COUNT,
        "severity": IndicatorSeverity.CRITICAL,
        "warn_threshold": 1,
        "crit_threshold": 1,
        "target_url": "/accounting?status=ENVIANDO",
        "roles": ["ADMIN", "CONTABILIDAD"],
        "order": 230,
    },
    {
        "key": "clientes_sin_alegra",
        "label": "Clientes sin sincronizar Alegra",
        "module": "ACCOUNTING",
        "unit": IndicatorUnit.COUNT,
        "severity": IndicatorSeverity.INFO,
        "warn_threshold": 50,
        "crit_threshold": 200,
        "target_url": "/accounting/customers",
        "roles": ["ADMIN", "CONTABILIDAD"],
        "order": 240,
    },
    {
        "key": "reembolsos_anulacion_pendiente",
        "label": "Reembolsos con anulación pendiente",
        "module": "ACCOUNTING",
        "unit": IndicatorUnit.COUNT,
        "severity": IndicatorSeverity.WARNING,
        "warn_threshold": 1,
        "crit_threshold": 10,
        "target_url": "/accounting/refunds",
        "roles": ["ADMIN", "CONTABILIDAD"],
        "order": 250,
    },
    # Sales
    {
        "key": "ventas_sin_vendedor",
        "label": "Ventas sin vendedor",
        "module": "SALES",
        "unit": IndicatorUnit.COUNT,
        "severity": IndicatorSeverity.WARNING,
        "warn_threshold": 5,
        "crit_threshold": 50,
        "target_url": "/sales",
        "roles": ["ADMIN", "VENTAS", "SUPERVISOR"],
        "order": 310,
    },
    {
        "key": "webhooks_fallidos",
        "label": "Eventos webhook fallidos",
        "module": "SALES",
        "unit": IndicatorUnit.COUNT,
        "severity": IndicatorSeverity.CRITICAL,
        "warn_threshold": 1,
        "crit_threshold": 5,
        "target_url": "/integrations/events",
        "roles": ["ADMIN", "VENTAS", "SUPERVISOR"],
        "order": 320,
    },
    # Logistics
    {
        "key": "guias_fallidas",
        "label": "Guías fallidas",
        "module": "LOGISTICS",
        "unit": IndicatorUnit.COUNT,
        "severity": IndicatorSeverity.CRITICAL,
        "warn_threshold": 1,
        "crit_threshold": 5,
        "target_url": "/logistics?status=GUIA_FALLIDA",
        "roles": ["ADMIN", "LOGISTICA", "SUPERVISOR"],
        "order": 410,
    },
    {
        "key": "pedidos_por_generar_guia",
        "label": "Pedidos por generar guía",
        "module": "LOGISTICS",
        "unit": IndicatorUnit.COUNT,
        "severity": IndicatorSeverity.WARNING,
        "warn_threshold": 20,
        "crit_threshold": 100,
        "target_url": "/logistics?status=POR_GENERAR",
        "roles": ["ADMIN", "LOGISTICA", "SUPERVISOR"],
        "order": 420,
    },
    {
        "key": "guias_con_warning",
        "label": "Guías con warning de destino",
        "module": "LOGISTICS",
        "unit": IndicatorUnit.COUNT,
        "severity": IndicatorSeverity.WARNING,
        "warn_threshold": 1,
        "crit_threshold": 20,
        "target_url": "/logistics?warning=true",
        "roles": ["ADMIN", "LOGISTICA", "SUPERVISOR"],
        "order": 430,
    },
    {
        "key": "listos_sin_despachar",
        "label": "Listos para enviar sin despachar",
        "module": "LOGISTICS",
        "unit": IndicatorUnit.COUNT,
        "severity": IndicatorSeverity.WARNING,
        "warn_threshold": 10,
        "crit_threshold": 50,
        "target_url": "/dispatch",
        "roles": ["ADMIN", "LOGISTICA", "SUPERVISOR"],
        "order": 440,
    },
    # Inventory
    {
        "key": "stock_bajo",
        "label": "Productos con stock bajo",
        "module": "INVENTORY",
        "unit": IndicatorUnit.COUNT,
        "severity": IndicatorSeverity.WARNING,
        "warn_threshold": 1,
        "crit_threshold": 10,
        "target_url": "/inventory/products",
        "roles": ["ADMIN", "LOGISTICA", "SUPERVISOR"],
        "order": 510,
    },
    {
        "key": "stock_negativo",
        "label": "Stock negativo",
        "module": "INVENTORY",
        "unit": IndicatorUnit.COUNT,
        "severity": IndicatorSeverity.CRITICAL,
        "warn_threshold": 1,
        "crit_threshold": 1,
        "target_url": "/inventory/products",
        "roles": ["ADMIN", "LOGISTICA", "SUPERVISOR"],
        "order": 520,
    },
]


def seed_dashboard(*, actor=None) -> dict:
    created = updated = 0
    for row in CATALOG:
        _, was_created = ControlIndicator.objects.update_or_create(
            key=row["key"],
            defaults={
                "label": row["label"],
                "module": row["module"],
                "description": row.get("description", ""),
                "unit": row["unit"],
                "severity": row["severity"],
                "warn_threshold": row.get("warn_threshold"),
                "crit_threshold": row.get("crit_threshold"),
                "target_url": row.get("target_url", ""),
                "visible": True,
                "roles": row.get("roles") or [],
                "order": row.get("order", 0),
            },
        )
        if was_created:
            created += 1
        else:
            updated += 1
    return {
        "created": created,
        "updated": updated,
        "total": ControlIndicator.objects.count(),
    }
