# Generated by Django 5.2.16 on 2026-07-23 04:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('SALE_NOTE', 'Nota de venta'), ('PRODUCT', 'Producto'), ('POLICY', 'Política'), ('SYMPTOM', 'Síntoma'), ('CASE', 'Caso')], db_index=True, max_length=32)),
                ('ref_type', models.CharField(blank=True, default='', max_length=64)),
                ('ref_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('content', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['kind', 'ref_type'], name='ai_document_kind_fa2c00_idx')],
            },
        ),
        migrations.CreateModel(
            name='Embedding',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chunk', models.TextField()),
                ('vector', models.JSONField(blank=True, default=list)),
                ('dimensions', models.PositiveIntegerField(default=64)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='embeddings', to='ai.document')),
            ],
            options={
                'indexes': [models.Index(fields=['document'], name='ai_embeddin_documen_06cf18_idx')],
            },
        ),
    ]
