# Generated by Django 5.2.6 on 2026-07-24 22:21

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountingAccount",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(max_length=32, unique=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "attribution",
                    models.CharField(
                        choices=[
                            ("ADMINISTRATIVO", "Administrativo"),
                            ("VENTAS", "Ventas"),
                            ("OPERACIONAL", "Operacional"),
                            ("COMPARTIDO", "Compartido"),
                            ("NIAT", "NIAT"),
                        ],
                        default="COMPARTIDO",
                        max_length=24,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="Bank",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=64, unique=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("BANK", "Banco"),
                            ("GATEWAY", "Pasarela"),
                            ("CASH", "Efectivo"),
                        ],
                        default="BANK",
                        max_length=16,
                    ),
                ),
                ("account_no", models.CharField(blank=True, max_length=64)),
                (
                    "importer",
                    models.CharField(
                        blank=True,
                        help_text="Parser CSV: bancolombia|mercadopago|bold|nequi",
                        max_length=32,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                (
                    "report_aliases",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Nombres de payment_account/medios que mapean a este banco en auditoría.",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="BankImportBatch",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("filename", models.CharField(blank=True, max_length=255)),
                ("rows_total", models.PositiveIntegerField(default=0)),
                ("rows_created", models.PositiveIntegerField(default=0)),
                ("rows_duplicated", models.PositiveIntegerField(default=0)),
                ("rows_errors", models.PositiveIntegerField(default=0)),
                ("dry_run", models.BooleanField(default=False)),
                ("errors", models.JSONField(blank=True, default=list)),
                (
                    "bank",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="import_batches",
                        to="finance.bank",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bank_import_batches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FinancialAccount",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(max_length=32, unique=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "full_label",
                    models.CharField(blank=True, db_index=True, max_length=255),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("VENTAS", "Ventas"),
                            ("COGS", "COGS"),
                            ("INGRESO", "Ingreso/Recaudo"),
                            ("COSTO", "Costo operativo"),
                            ("GASTO", "Gasto"),
                            ("PASIVO", "Otros pasivos"),
                            ("AJUSTE", "Ajuste"),
                            ("ADMIN", "Gasto administrativo"),
                        ],
                        default="GASTO",
                        max_length=16,
                    ),
                ),
                ("is_leaf", models.BooleanField(default=True)),
                (
                    "sign",
                    models.CharField(
                        blank=True,
                        choices=[("IN", "Entra"), ("OUT", "Sale")],
                        max_length=8,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("order", models.IntegerField(default=0)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="finance.financialaccount",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "code"],
            },
        ),
        migrations.CreateModel(
            name="ClassificationRule",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("concept_contains", models.CharField(max_length=255)),
                ("attribution", models.CharField(blank=True, max_length=24)),
                ("is_interbank", models.BooleanField(default=False)),
                ("priority", models.IntegerField(default=100)),
                ("active", models.BooleanField(default=True)),
                (
                    "auto_apply",
                    models.BooleanField(
                        default=True,
                        help_text="Si true, asigna al importar; si false solo sugiere.",
                    ),
                ),
                (
                    "accounting_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rules",
                        to="finance.accountingaccount",
                    ),
                ),
                (
                    "bank",
                    models.ForeignKey(
                        blank=True,
                        help_text="Vacío = aplica a todos los bancos",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="classification_rules",
                        to="finance.bank",
                    ),
                ),
                (
                    "financial_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rules",
                        to="finance.financialaccount",
                    ),
                ),
            ],
            options={
                "ordering": ["priority", "name"],
            },
        ),
        migrations.CreateModel(
            name="EfeMonthClose",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("year", models.PositiveIntegerField()),
                ("month", models.PositiveSmallIntegerField()),
                ("closed_at", models.DateTimeField(auto_now_add=True)),
                ("note", models.CharField(blank=True, max_length=512)),
                (
                    "unclassified_pct",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=5
                    ),
                ),
                (
                    "closed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="efe_closes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-year", "-month"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("year", "month"), name="uq_efe_month_close"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="EfeBudget",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("year", models.PositiveIntegerField()),
                ("month", models.PositiveSmallIntegerField()),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=16
                    ),
                ),
                (
                    "financial_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="budgets",
                        to="finance.financialaccount",
                    ),
                ),
            ],
            options={
                "ordering": ["year", "month", "financial_account__code"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("financial_account", "year", "month"),
                        name="uq_efe_budget_account_ym",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="BankMovement",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                ("value", models.DecimalField(decimal_places=2, max_digits=16)),
                (
                    "item",
                    models.CharField(
                        choices=[("INGRESO", "Ingreso"), ("EGRESO", "Egreso")],
                        max_length=16,
                    ),
                ),
                ("concept", models.CharField(blank=True, max_length=512)),
                ("reference", models.CharField(blank=True, max_length=128)),
                ("comment", models.CharField(blank=True, max_length=512)),
                ("attribution", models.CharField(blank=True, max_length=24)),
                ("is_interbank", models.BooleanField(default=False)),
                (
                    "total_tax",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=14
                    ),
                ),
                (
                    "retefuente",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=14
                    ),
                ),
                (
                    "reteica",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=14
                    ),
                ),
                (
                    "reteiva",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=14
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("POR_CLASIFICAR", "Por clasificar"),
                            ("CLASIFICADO", "Clasificado"),
                            ("CONCILIADO", "Conciliado"),
                        ],
                        db_index=True,
                        default="POR_CLASIFICAR",
                        max_length=24,
                    ),
                ),
                ("alegra_synced", models.BooleanField(default=False)),
                ("alegra_id", models.CharField(blank=True, max_length=64)),
                ("dedupe_hash", models.CharField(db_index=True, max_length=64)),
                ("tx_code", models.CharField(blank=True, max_length=32)),
                (
                    "accounting_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="movements",
                        to="finance.accountingaccount",
                    ),
                ),
                (
                    "bank",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movements",
                        to="finance.bank",
                    ),
                ),
                (
                    "import_batch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="movements",
                        to="finance.bankimportbatch",
                    ),
                ),
                (
                    "financial_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="movements",
                        to="finance.financialaccount",
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "date"], name="finance_ban_status_bbbbb1_idx"
                    ),
                    models.Index(
                        fields=["bank", "date"], name="finance_ban_bank_id_a4b77a_idx"
                    ),
                    models.Index(
                        fields=["is_interbank", "date"],
                        name="finance_ban_is_inte_4fdad1_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("bank", "dedupe_hash"), name="uq_bankmov_bank_dedupe"
                    )
                ],
            },
        ),
    ]
