# Generated by Django 5.2.16 on 2026-07-23 02:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=128, unique=True)),
                ('is_system', models.BooleanField(default=False, help_text='True para ECOMMERCE/FERIAS (no personas).')),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('aliases', models.JSONField(blank=True, default=list, help_text='Alias de texto crudo, p.ej. ["Marina","Maji","Lau"].')),
                ('needs_review', models.BooleanField(default=False, help_text='Creado automáticamente desde un commercial_raw desconocido.')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendedores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vendedor',
                'verbose_name_plural': 'Vendedores',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['active', 'is_system'], name='sellers_ven_active_cbad87_idx'), models.Index(fields=['needs_review', 'active'], name='sellers_ven_needs_r_e7847d_idx')],
            },
        ),
    ]
