# Generated by Django 5.2.6 on 2026-07-23 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sellers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="vendedor",
            name="monthly_goal",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=None,
                help_text="Meta mensual del vendedor (COP). Null → usa business.sales_goal_month.",
                max_digits=14,
                null=True,
            ),
        ),
    ]
