# Generated by Django 5.2.16 on 2026-07-23 04:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sales', '0001_initial'),
        ('sellers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=64)),
                ('city', models.CharField(blank=True, default='', max_length=128)),
                ('source', models.CharField(blank=True, db_index=True, default='manual', help_text='web, feria, referido, kommo, manual…', max_length=64)),
                ('status', models.CharField(choices=[('NUEVO', 'Nuevo'), ('CONTACTADO', 'Contactado'), ('CALIFICADO', 'Calificado'), ('CONVERTIDO', 'Convertido'), ('DESCARTADO', 'Descartado')], db_index=True, default='NUEVO', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('converted_sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_leads', to='sales.consolidatedsale')),
                ('seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='sellers.vendedor')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'source'], name='leads_lead_status_b280c3_idx'), models.Index(fields=['seller', 'status'], name='leads_lead_seller__acb6f4_idx')],
            },
        ),
    ]
