# Generated by Django 5.2.16 on 2026-07-23 02:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SettingAudit',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(db_index=True, max_length=128)),
                ('action', models.CharField(choices=[('CREATED', 'Creado'), ('UPDATED', 'Actualizado'), ('ROTATED', 'Rotado'), ('DELETED', 'Eliminado')], max_length=16)),
                ('old_value_masked', models.CharField(blank=True, max_length=64)),
                ('new_value_masked', models.CharField(blank=True, max_length=64)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SettingValue',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(db_index=True, max_length=128, unique=True)),
                ('value', models.TextField(blank=True, default='')),
                ('encrypted', models.BinaryField(blank=True, null=True)),
                ('is_secret', models.BooleanField(default=False)),
                ('version', models.PositiveIntegerField(default=1)),
            ],
            options={
                'ordering': ['key'],
            },
        ),
    ]
