# Generated by Django 5.2.16 on 2026-07-23 02:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('WOOCOMMERCE', 'WooCommerce'), ('KOMMO', 'Kommo'), ('ENVIA', 'Envia'), ('ALEGRA', 'Alegra'), ('AI', 'IA'), ('INTERNAL', 'Interno')], db_index=True, max_length=32)),
                ('method', models.CharField(default='POST', max_length=16)),
                ('url', models.TextField()),
                ('request_headers', models.JSONField(blank=True, default=dict)),
                ('request_body', models.JSONField(blank=True, default=dict)),
                ('response_status', models.PositiveIntegerField(blank=True, null=True)),
                ('response_body', models.JSONField(blank=True, default=dict)),
                ('latency_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('success', models.BooleanField(default=False)),
                ('error', models.TextField(blank=True)),
                ('ref_type', models.CharField(blank=True, max_length=64)),
                ('ref_id', models.CharField(blank=True, db_index=True, max_length=64)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RawWebhookEvent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('WOOCOMMERCE', 'WooCommerce'), ('KOMMO', 'Kommo'), ('ENVIA', 'Envia'), ('ALEGRA', 'Alegra'), ('AI', 'IA'), ('INTERNAL', 'Interno')], db_index=True, max_length=32)),
                ('event_type', models.CharField(db_index=True, max_length=64)),
                ('received_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('headers', models.JSONField(blank=True, default=dict)),
                ('payload', models.JSONField(default=dict)),
                ('signature', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('RECEIVED', 'Recibido'), ('PROCESSED', 'Procesado'), ('FAILED', 'Fallido'), ('IGNORED', 'Ignorado')], db_index=True, default='RECEIVED', max_length=16)),
                ('error', models.TextField(blank=True)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('dedupe_key', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'ordering': ['-received_at'],
                'indexes': [models.Index(fields=['source', 'status'], name='integration_source_0b5f54_idx'), models.Index(fields=['event_type', 'status'], name='integration_event_t_32fe36_idx')],
            },
        ),
    ]
