# Generated by Django 5.2.16 on 2026-07-23 02:27

import django.contrib.gis.db.models.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeoCatalog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('municipality', models.CharField(db_index=True, max_length=128)),
                ('municipality_code', models.CharField(max_length=16, unique=True)),
                ('department', models.CharField(max_length=128)),
                ('department_iso', models.CharField(db_index=True, max_length=8)),
                ('point', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('search', models.CharField(db_index=True, max_length=256)),
            ],
            options={
                'ordering': ['department', 'municipality'],
                'indexes': [models.Index(fields=['search'], name='geo_geocata_search_496efd_idx'), models.Index(fields=['department_iso', 'municipality'], name='geo_geocata_departm_9ab365_idx')],
            },
        ),
    ]
