# Generated by Django 5.2.16 on 2026-07-23 12:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=128, unique=True)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('aliases', models.JSONField(blank=True, default=list, help_text='Alias de texto crudo, p.ej. ["nequi","Nequi Colombia"].')),
                ('is_system', models.BooleanField(default=False, help_text='Semilla del sistema (Nequi, Efectivo…). Se puede desactivar, no borrar.')),
            ],
            options={
                'verbose_name': 'Medio de pago',
                'verbose_name_plural': 'Medios de pago',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='consolidatedsale',
            name='payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='sales.paymentmethod'),
        ),
        migrations.AddField(
            model_name='ecommercesale',
            name='payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_sales', to='sales.paymentmethod'),
        ),
        migrations.AddField(
            model_name='feriasale',
            name='payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_sales', to='sales.paymentmethod'),
        ),
        migrations.AddField(
            model_name='kommosale',
            name='payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_sales', to='sales.paymentmethod'),
        ),
        migrations.AddField(
            model_name='manualsale',
            name='payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_sales', to='sales.paymentmethod'),
        ),
    ]
