# Generated by Django 5.2.16 on 2026-07-23 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_payment_methods'),
    ]

    operations = [
        migrations.AddField(
            model_name='consolidatedsale',
            name='fulfillment_type',
            field=models.CharField(choices=[('ENVIA', 'Envia (guía)'), ('DOMICILIO', 'Domicilio fuera de Envia'), ('OFICINA', 'Visita / recoger en oficina')], db_index=True, default='ENVIA', help_text='ENVIA → guías Envia. DOMICILIO/OFICINA → no generan guía.', max_length=16),
        ),
        migrations.AddField(
            model_name='ecommercesale',
            name='fulfillment_type',
            field=models.CharField(choices=[('ENVIA', 'Envia (guía)'), ('DOMICILIO', 'Domicilio fuera de Envia'), ('OFICINA', 'Visita / recoger en oficina')], db_index=True, default='ENVIA', help_text='ENVIA → guías Envia. DOMICILIO/OFICINA → no generan guía.', max_length=16),
        ),
        migrations.AddField(
            model_name='feriasale',
            name='fulfillment_type',
            field=models.CharField(choices=[('ENVIA', 'Envia (guía)'), ('DOMICILIO', 'Domicilio fuera de Envia'), ('OFICINA', 'Visita / recoger en oficina')], db_index=True, default='ENVIA', help_text='ENVIA → guías Envia. DOMICILIO/OFICINA → no generan guía.', max_length=16),
        ),
        migrations.AddField(
            model_name='kommosale',
            name='fulfillment_type',
            field=models.CharField(choices=[('ENVIA', 'Envia (guía)'), ('DOMICILIO', 'Domicilio fuera de Envia'), ('OFICINA', 'Visita / recoger en oficina')], db_index=True, default='ENVIA', help_text='ENVIA → guías Envia. DOMICILIO/OFICINA → no generan guía.', max_length=16),
        ),
        migrations.AddField(
            model_name='manualsale',
            name='fulfillment_type',
            field=models.CharField(choices=[('ENVIA', 'Envia (guía)'), ('DOMICILIO', 'Domicilio fuera de Envia'), ('OFICINA', 'Visita / recoger en oficina')], db_index=True, default='ENVIA', help_text='ENVIA → guías Envia. DOMICILIO/OFICINA → no generan guía.', max_length=16),
        ),
        migrations.AlterField(
            model_name='consolidatedsale',
            name='requires_shipping',
            field=models.BooleanField(default=True, help_text='Derivado de fulfillment_type: True solo si ENVIA.'),
        ),
        migrations.AlterField(
            model_name='ecommercesale',
            name='requires_shipping',
            field=models.BooleanField(default=True, help_text='Derivado de fulfillment_type: True solo si ENVIA.'),
        ),
        migrations.AlterField(
            model_name='feriasale',
            name='requires_shipping',
            field=models.BooleanField(default=True, help_text='Derivado de fulfillment_type: True solo si ENVIA.'),
        ),
        migrations.AlterField(
            model_name='kommosale',
            name='requires_shipping',
            field=models.BooleanField(default=True, help_text='Derivado de fulfillment_type: True solo si ENVIA.'),
        ),
        migrations.AlterField(
            model_name='manualsale',
            name='requires_shipping',
            field=models.BooleanField(default=True, help_text='Derivado de fulfillment_type: True solo si ENVIA.'),
        ),
    ]
